[[constraint]]
  branch = "master"
  name = "code.cloudfoundry.org/lager"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.12.26"

[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "1.4.0"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "1.2.0"

[[constraint]]
  name = "github.com/phayes/freeport"
  version = "1.0.2"

[[constraint]]
  branch = "master"
  name = "github.com/pivotal-cf/brokerapi"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.1.0"
